name: drought
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.5.1
  - r-tidyverse=2.0.0
  - r-ragg=1.3.3
  - r-systemfonts=1.1.0
  - r-textshaping=0.4.0
  - r-archive=1.1.12
  - r-lubridate=1.9.4
  - r-glue=1.8.0
  - r-rmarkdown=2.30
  - snakemake=9.11.4
  - wget=1.21.4
  - graphviz=8.1.0
  - coreutils=9.8
