name: Run Drought Index Workflow
run-name: ${{ github.actor }} is running snakemake workflow
on: 
  #push:
  schedule:
    - cron: '10 00 * * *'
jobs:
  Run-Drought-Index-Workflow:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls
      - name: Get working directory
        run: |
          pwd
      - name: Prepare enviroment
        run: |
          mkdir -p data
          sudo apt-get update && sudo apt-get install -y wget git
      - name: Snakemake Workflow
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--cores 1 --sdm conda --conda-cleanup-pkgs cache'
          stagein: ''
      - name: Configure git on runner
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub"
      - name: Commit changes to repository
        run: |
          git add visual/world_drought.png
          git commit -m "New day's rendering" || echo "No changes to commit"
          git push origin main
      - run: echo "ğŸ This job's status is ${{ job.status }}."
